ALTER TABLE users
ALTER COLUMN id SET DATA TYPE TEXT;

ALTER TABLE check_ins
ALTER COLUMN id SET DATA TYPE TEXT;

ALTER TABLE gyms
ALTER COLUMN id SET DATA TYPE TEXT;

ALTER TABLE users
DROP COLUMN created_at;